MULTIGRID:
  SHORT_CYCLE: False
  LONG_CYCLE: False
TRAIN:
  ENABLE: False
  DATASET: microexpressions
  BATCH_SIZE: 8
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 10
  AUTO_RESUME: True
DATA:
  NUM_FRAMES: 64
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3, 3]
  PATH_TO_DATA_DIR: /home/khen_proj_1/PycharmProjects/slowfast_test/slowfast/data/MicroExpressions
  PATH_LABEL_SEPARATOR: ","
SLOWFAST:
  ALPHA: 8
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.1
  LR_POLICY: steps_with_relative_lrs
  LRS: [1, 0.1, 0.01, 0.001, 0.0001, 0.00001]
  STEPS: [0, 94, 154, 196]
  MAX_EPOCH: 239
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 34.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 25
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: microexpressions
  BATCH_SIZE: 8
  SAVE_RESULTS_PATH: TestResults.bin
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 0
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: /home/khen_proj_1/yuvaltuval/MicroExpressionsFaceRecognition/output/SlowFast/test/
DEMO:
  ENABLE: False
  LABEL_FILE_PATH: /home/khen_proj_1/PycharmProjects/slowfast_test/slowfast/data/MicroExpressions/classids.json
  INPUT_VIDEO: /home/khen_proj_1/PycharmProjects/slowfast_test/slowfast/data/MicroExpressions/SAMM_6/006_1_2.mp4
  OUTPUT_FILE: /test.mp4
TENSORBOARD:
  ENABLE: True
  CLASS_NAMES_PATH: /home/khen_proj_1/PycharmProjects/slowfast_test/slowfast/data/MicroExpressions/classids.json
  CONFUSION_MATRIX:
    ENABLE: False
    SUBSET_PATH: /home/khen_proj_1/PycharmProjects/slowfast_test/slowfast/data/MicroExpressions/classes.txt
  HISTOGRAM:
    ENABLE: False
    TOPK: 5
    SUBSET_PATH: /home/khen_proj_1/PycharmProjects/slowfast_test/slowfast/data/MicroExpressions/classes.txt
  MODEL_VIS:
    ENABLE: True
    MODEL_WEIGHTS: False
    ACTIVATIONS: False
    INPUT_VIDEO: False
    GRAD_CAM:
      ENABLE: True
      LAYER_LIST: ['s5/pathway1_res2', 's5/pathway0_res2']
  WRONG_PRED_VIS:
    ENABLE: False
    SUBSET_PATH: /home/khen_proj_1/PycharmProjects/slowfast_test/slowfast/data/MicroExpressions/classes.txt
